prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    retention: 6h
    storageSpec: {}

grafana:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  adminPassword: admin123
  persistence:
    enabled: false
  env:
    GF_PLUGINS_PREINSTALL_DISABLED: "true"

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 30m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
