apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notification-postgres-policy
spec:
  podSelector:
    matchLabels:
      app: notification-postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: notification-service
      ports:
        - protocol: TCP
          port: 5432
